defaults:
  - encoder: Omni


instance:
  _target_: models.networks.Fine_tuning.Fine
  encoder: ${model.network.encoder}
  path: ''
  output_size: ${model.network.encoder.embed_dim}
  inter_dim: []
  p_drop: 0.2
  freeze: False
  n_class: ${dataset.num_classes}
  modalities: ${modalities}
  last_block: False
  pooling_method: 'token'
  proj_only: False