defaults:
  - encoder: PseTae
  - mlp: mlp

instance:
  _target_: models.networks.MonoModal.MonoModal
  encoder: ${model.network.encoder}
  mlp: ${model.network.mlp}
  modalities: ${modalities}
  omni: False
