_target_: models.networks.encoder.ViT.VisionTransformer
modalities: ${modalities}
img_size: 300
in_chans: 4
patch_size: 50
embed_dim: 256
depth: 12
num_heads: 8
mlp_ratio: 4.
global_pool: 'avg'
output_dim: 128
res: True
gp_norm: 4
drop_rate: 0.2
pos_drop_rate: 0.2
patch_drop_rate: 0.2
attn_drop_rate: 0.2
drop_path_rate: 0.2
