_target_: models.networks.encoder.ViT.VisionTransformer
modalities: ${modalities}
img_size: 6
in_chans: 10
patch_size: 1
embed_dim: 128
depth: 4
num_heads: 8
mlp_ratio: 4.
global_pool: 'max'
output_dim: 128
res: False
gp_norm: 4
drop_rate: 0.2
pos_drop_rate: 0.2
patch_drop_rate: 0.2
attn_drop_rate: 0.2
drop_path_rate: 0.2
