# @package _global_

defaults:
  - override /dataset: FLAIR
  - override /model/network: Late_fusion_ScaleMAE_FLAIR
  - override /dataset/train_transform: MAE 
  - override /dataset/test_transform: MAE

model:
  name: "ScaleMAE_Late_fusion"
  optimizer:
    lr: 2e-4
  network:
    instance:
      encoder:
        aerial:
          path: ${paths.log_dir}/FLAIR_ScaleMAE_Aerial/checkpoints/last.ckpt
        s2-4season-median:
          path: ${paths.log_dir}/FLAIR_ScaleMAE_S2_4s/checkpoints/last.ckpt
    mlp:
      instance:
        initial_dim: 256
        
dataset:
  train_transform:
    s2_size: 48
  test_transform:
    s2_size: 48

callbacks:
  early_stopping:
    monitor: "val/F1_Score_macro"
    mode: "max"
    patience: 10

modalities:
  - "aerial"
  - "s2-4season-median"
