# @package _global_

defaults:
  - override /dataset: FLAIR
  - override /model/network: Fine_tuning
  - override /model/network/encoder: Omni

model:
  name: "OmniSAT_FineTuning_Aerial"
  optimizer:
    lr: 2e-4
  network:
    instance:
      path: ${paths.log_dir}/FLAIR_OmniSAT/checkpoints/last.ckpt
      encoder:
        num_patches: 100
        projectors:
          aerial:
            in_chans: 5

callbacks:
  early_stopping:
    monitor: "val/F1_Score_macro"
    mode: "max"
    patience: 10

modalities:
  - "aerial"