# @package _global_

defaults:
  - override /dataset: FLAIR
  - override /model/network: ScaleMAE
  - override /dataset/train_transform: MAE
  - override /dataset/test_transform: MAE
  - override /model: MAE

model:
  name: "ScaleMAE_S2-4s"
  optimizer:
    lr: 1e-4
  network:
    instance:
      channel_groups: [[0, 1, 2, 6], [3, 4, 5, 7], [8, 9], [10, 11, 12, 16], [13, 14, 15, 17], [18, 19], [20, 21, 22, 26], [23, 24, 25, 27], [28, 29], [30, 31, 32, 36], [33, 34, 35, 37], [38, 39]]
      channel_group_gsds: [10, 20, 20, 10, 20, 20, 10, 20, 20, 10, 20, 20]
      img_size: 48

dataset:
  train_transform:
    size: 48
  test_transform:
    size: 48

modalities:
  - "s2-4season-median"
