# @package _global_

defaults:
  - override /dataset: FLAIR
  - override /model/network/encoder: Omni

model:
  name: "Omni_Aerial"
  optimizer:
    lr: 2e-3
  network:
    instance:
      omni: True
      encoder:
        num_patches: 100
        projectors:
          aerial:
            in_chans: 5
    mlp:
      instance:
        initial_dim: ${model.network.encoder.embed_dim}

callbacks:
  early_stopping:
    monitor: "val/F1_Score_macro"
    mode: "max"
    patience: 10

partition: 0.1
modalities:
  - "aerial"

