# @package _global_

defaults:
  - override /dataset: Pastis
  - override /model/network: Fine_tuning_croma
  - override /dataset/train_transform: CROMA
  - override /dataset/test_transform: CROMA

model:
  name: "Croma_FineTuning_MM"
  optimizer:
    lr: 2e-5
  network:
    instance:
      pretrained_path: ${paths.log_dir}/PASTIS-R_CROMA/checkpoints/last.ckpt
      modality: 'both'
      in_c_sar: 12
      in_c_opt: 40

callbacks:
  early_stopping:
    monitor: "val/F1_Score_macro"
    mode: "max"
    patience: 10

modalities:
  - "s2-4season-median"
  - "s1-4season-median"