# @package _global_

defaults:
  - override /dataset: Pastis
  - override /model/network: ScaleMAE
  - override /dataset/train_transform: MAE
  - override /dataset/test_transform: MAE
  - override /model: MAE

model:
  name: "ScaleMAE_S2"
  optimizer:
    lr: 1e-4
  network:
    instance:
      channel_groups: [[0, 1, 2, 6], [3, 4, 5, 7], [8, 9]]
      channel_group_gsds: [10, 20, 20]
      img_size: 48

dataset:
  train_transform:
    size: 48
  test_transform:
    size: 48

modalities:
  - "s2-median"
