# @package _global_

defaults:
  - override /dataset: Pastis
  - override /model/network: Late_fusion_UTAE

model:
  name: "UTAE_Late_fusion"
  optimizer:
    lr: 2e-3
  network:
    mlp:
      instance:
        initial_dim: 384

callbacks:
  early_stopping:
    monitor: "val/F1_Score_macro"
    mode: "max"
    patience: 10

modalities:
  - "aerial"
  - "s2"
  - "s1-asc"
