# @package _global_

defaults:
  - override /model/network/encoder: Omni

model:
  name: "Omni_Aerial"
  optimizer:
    lr: 2e-4
  network:
    instance:
      omni: True
    mlp:
      instance:
        initial_dim: ${model.network.encoder.embed_dim}
        hidden_dim: []

callbacks:
  early_stopping:
    monitor: "val/F1_Score_macro"
    mode: "max"
    patience: 10

modalities:
  - "aerial"

