# @package _global_

defaults:
  - override /model/network: ScaleMAE
  - override /dataset/train_transform: MAE
  - override /dataset/test_transform: MAE
  - override /model: MAE

model:
  name: "ScaleMAE_Aerial"
  optimizer:
    lr: 1e-4

modalities:
  - "aerial"
