# @package _global_

defaults:
  - override /model/network: Fine_tuning_MAE
  - override /dataset/train_transform: MAE
  - override /dataset/test_transform: MAE

model:
  name: "SatMAE_FineTuning_S2"
  optimizer:
    lr: 2e-4
  network:
    instance:
      path: ${paths.log_dir}/TreeSat_SatMAE_S2/checkpoints/last.ckpt
      encoder: 
        channel_groups: [[0, 1, 2, 6], [3, 4, 5, 7], [8, 9]]

callbacks:
  early_stopping:
    monitor: "val/F1_Score_macro"
    mode: "max"
    patience: 10

modalities:
  - "s2-mono"

