# @package _global_

defaults:
  - override /model/network: Late_fusion_MLP

model:
  name: "MLP_Late_fusion"
  optimizer:
    lr: 2e-3
  network:
    instance:
      encoder:
        aerial:
          reduce: True
    mlp:
      instance:
        initial_dim: 256

callbacks:
  early_stopping:
    monitor: "val/F1_Score_macro"
    mode: "max"
    patience: 10

modalities:
  - "aerial"
  - "s1-mono"
  - "s2-mono"
