# @package _global_

defaults:
  - override /model/network: SatMAE
  - override /dataset/train_transform: MAE
  - override /dataset/test_transform: MAE
  - override /model: MAE

model:
  name: "SatMAE_S2"
  optimizer:
    lr: 1e-4
  network:
    instance:
      channel_groups: [[0, 1, 2, 6], [3, 4, 5, 7], [8, 9]]

modalities:
  - "s2-mono"
