# @package _global_

defaults:
  - override /model/network/encoder: ViT_s
  - override /model/network/mlp: identity

model:
  name: "ViT_S1"
  network:
    encoder:
      in_chans: 3
      output_dim: 15
  optimizer:
    lr: 0.00001

callbacks:
  early_stopping:
    monitor: "val/F1_Score_macro"
    mode: "max"
    patience: 10

modalities:
  - "s1-mono"