# @package _global_

defaults:
  - override /model/network: Fine_tuning_croma
  - override /dataset/train_transform: CROMA
  - override /dataset/test_transform: CROMA

model:
  name: "Croma_FineTuning_S2"
  optimizer:
    lr: 2e-5
  network:
    instance:
      pretrained_path: ${paths.log_dir}/TreeSat_CROMA/checkpoints/last.ckpt
      modality: 'optical'
      in_c_opt: 12

callbacks:
  early_stopping:
    monitor: "val/F1_Score_macro"
    mode: "max"
    patience: 10

modalities:
  - "s2-mono"