# @package _global_

defaults:
  - override /model/network/encoder: ViT
  - override /model/network/mlp: identity

model:
  name: "ViT_Aerial"
  network:
    encoder:
      output_dim: 15
  optimizer:
    lr: 0.001

callbacks:
  early_stopping:
    monitor: "val/F1_Score_macro"
    mode: "max"
    patience: 10

modalities:
  - "aerial"