# @package _global_

defaults:
  - override /model/network: Fine_tuning

model:
  name: "OmniSAT_Probing_MM"
  optimizer:
    lr: 2e-3
  network:
    instance:
      freeze: True
      path: ${paths.log_dir}/TreeSat_OmniSAT/checkpoints/last.ckpt

callbacks:
  early_stopping:
    monitor: "val/F1_Score_macro"
    mode: "max"
    patience: 10

modalities:
  - "aerial"
  - "s2"
  - "s1-asc"   