# @package _global_

defaults:
  - override /model/network/encoder: MLP
  - override /model/network/mlp: identity

model:
  name: "MLP_S1"
  network:
    encoder:
      n_bands: 3
  optimizer:
    lr: 0.001

callbacks:
  early_stopping:
    monitor: "val/F1_Score_macro"
    mode: "max"
    patience: 10

modalities:
  - "s1-mono"