# @package _global_

defaults:
  - override /model/network: Late_fusion_SatMAE
  - override /dataset/train_transform: MAE 
  - override /dataset/test_transform: MAE

model:
  name: "SatMAE_Late_fusion"
  optimizer:
    lr: 2e-4
  network:
    instance:
      encoder:
        aerial:
          path: ${paths.log_dir}/TreeSat_SatMAE_Aerial/checkpoints/last.ckpt
        s2-mono:
          path: ${paths.log_dir}/TreeSat_SatMAE_S2/checkpoints/last.ckpt
    mlp:
      instance:
        initial_dim: 256

callbacks:
  early_stopping:
    monitor: "val/F1_Score_macro"
    mode: "max"
    patience: 10

modalities:
  - "aerial"
  - "s2-mono"
