# @package _global_

defaults:
  - override /model/network: Fine_tuning_MAE
  - override /dataset/train_transform: MAE
  - override /dataset/test_transform: MAE

model:
  name: "ScaleMAE_FineTuning_Aerial"
  optimizer:
    lr: 2e-4
  network:
    instance:
      path: ${paths.log_dir}/TreeSat_ScaleMAE_Aerial/checkpoints/last.ckpt
      encoder: 
        _target_: models.networks.encoder.ScaleViT.ScaleVitEncoder
        img_size: 224
        patch_size: 8
        channel_groups: [[0,1,2,3]]
        in_chans: 4
        channel_group_gsds: [0.1]
        embed_dim: 384
        depth: 12
        num_heads: 16
        mlp_ratio: 4.

callbacks:
  early_stopping:
    monitor: "val/F1_Score_macro"
    mode: "max"
    patience: 10

modalities:
  - "aerial"
