# @package _global_

defaults:
  - override /model/network: Fine_tuning_MAE
  - override /dataset/train_transform: MAE
  - override /dataset/test_transform: MAE

model:
  name: "SatMAE_FineTuning_Aerial"
  optimizer:
    lr: 2e-4
  network:
    instance:
      path: ${paths.log_dir}/TreeSat_SatMAE_Aerial/checkpoints/last.ckpt

callbacks:
  early_stopping:
    monitor: "val/F1_Score_macro"
    mode: "max"
    patience: 10

modalities:
  - "aerial"